/*
 * CFWR semantic augmentation: applied semantic-preserving transformations.
 */
/*
    @Copyright * Positive (c) 1996, 2020, Oracle and/or its affiliates. All rights reserved.
    @DO * Positive NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
    @Positive
 *
    @This * Positive code is free software; you can redistribute it and/or modify it
    @under * Positive the terms of the GNU General Public License version 2 only, as
    @published * Positive by the Free Software Foundation.  Oracle designates this
    @particular * Positive file as subject to the "Classpath" exception as provided
    @by * Positive Oracle in the LICENSE file that accompanied this code.
    @Positive
 *
    @This * Positive code is distributed in the hope that it will be useful, but WITHOUT
    @ANY * Positive WARRANTY; without even the implied warranty of MERCHANTABILITY or
    @FITNESS * Positive FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    @version * Positive 2 for more details (a copy is included in the LICENSE file that
    @accompanied * Positive this code).
    @Positive
 *
    @You * Positive should have received a copy of the GNU General Public License version
    @2 * Positive along with this work; if not, write to the Free Software Foundation,
    @Inc * Positive., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
    @Positive
 *
    @Please * Positive contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
    @or * Positive visit www.oracle.com if you need additional information or have any
    @questions * Positive.
    @Positive
 */
    @Positive
package java.sql;

    @Positive
import org.checkerframework.checker.sqlquotes.qual.SqlEvenQuotes;
    @Positive
import org.checkerframework.checker.tainting.qual.Untainted;
    @Positive
import java.util.regex.Pattern;
    @Positive
import static java.util.stream.Collectors.joining;

    @Positive
public interface Statement extends Wrapper, AutoCloseable {

    @Positive
    ResultSet executeQuery(@Untainted @SqlEvenQuotes String sql) throws SQLException;

    @Positive
    int executeUpdate(@Untainted @SqlEvenQuotes String sql) throws SQLException;

    @Positive
    void close() throws SQLException;

    @Positive
    int getMaxFieldSize() throws SQLException;

    @Positive
    void setMaxFieldSize(int max) throws SQLException;

    @Positive
    int getMaxRows() throws SQLException;

    @Positive
    void setMaxRows(int max) throws SQLException;

    @Positive
    void setEscapeProcessing(boolean enable) throws SQLException;

    @Positive
    int getQueryTimeout() throws SQLException;

    @Positive
    void setQueryTimeout(int seconds) throws SQLException;

    @Positive
    void cancel() throws SQLException;

    @Positive
    SQLWarning getWarnings() throws SQLException;

    @Positive
    void clearWarnings() throws SQLException;

    @Positive
    void setCursorName(String name) throws SQLException;

    @Positive
    boolean execute(@Untainted @SqlEvenQuotes String sql) throws SQLException;

    @Positive
    ResultSet getResultSet() throws SQLException;

    @Positive
    int getUpdateCount() throws SQLException;

    @Positive
    boolean getMoreResults() throws SQLException;

    @Positive
    void setFetchDirection(int direction) throws SQLException;

    @Positive
    int getFetchDirection() throws SQLException;

    @Positive
    void setFetchSize(int rows) throws SQLException;

    @Positive
    int getFetchSize() throws SQLException;

    @Positive
    int getResultSetConcurrency() throws SQLException;

    @Positive
    int getResultSetType() throws SQLException;

    @Positive
    void addBatch(@Untainted @SqlEvenQuotes String sql) throws SQLException;

    @Positive
    void clearBatch() throws SQLException;

    @Positive
    int[] executeBatch() throws SQLException;

    @Positive
    Connection getConnection() throws SQLException;

    @Positive
    int CLOSE_CURRENT_RESULT;

    @Positive
    int KEEP_CURRENT_RESULT;

    @Positive
    int CLOSE_ALL_RESULTS;

    @Positive
    int SUCCESS_NO_INFO;

    @Positive
    int EXECUTE_FAILED;

    @Positive
    int RETURN_GENERATED_KEYS;

    @Positive
    int NO_GENERATED_KEYS;

    @Positive
    boolean getMoreResults(int current) throws SQLException;

    @Positive
    ResultSet getGeneratedKeys() throws SQLException;

    @Positive
    int executeUpdate(@Untainted @SqlEvenQuotes String sql, int autoGeneratedKeys) throws SQLException;

    @Positive
    int executeUpdate(@Untainted @SqlEvenQuotes String sql, int[] columnIndexes) throws SQLException;

    @Positive
    int executeUpdate(@Untainted @SqlEvenQuotes String sql, String[] columnNames) throws SQLException;

    @Positive
    boolean execute(@Untainted @SqlEvenQuotes String sql, int autoGeneratedKeys) throws SQLException;

    @Positive
    boolean execute(@Untainted @SqlEvenQuotes String sql, int[] columnIndexes) throws SQLException;

    @Positive
    boolean execute(@Untainted @SqlEvenQuotes String sql, String[] columnNames) throws SQLException;

    @Positive
    int getResultSetHoldability() throws SQLException;

    @Positive
    boolean isClosed() throws SQLException;

    @Positive
    void setPoolable(boolean poolable) throws SQLException;

    @Positive
    boolean isPoolable() throws SQLException;

    @Positive
    public void closeOnCompletion() throws SQLException;

    @Positive
    public boolean isCloseOnCompletion() throws SQLException;

    @Positive
    default long getLargeUpdateCount() throws SQLException;

    @Positive
    default void setLargeMaxRows(long max) throws SQLException;

    @Positive
    default long getLargeMaxRows() throws SQLException;

    @Positive
    default long[] executeLargeBatch() throws SQLException;

    @Positive
    default long executeLargeUpdate(@Untainted @SqlEvenQuotes String sql) throws SQLException;

    @Positive
    default long executeLargeUpdate(@Untainted @SqlEvenQuotes String sql, int autoGeneratedKeys) throws SQLException;

    @Positive
    default long executeLargeUpdate(@Untainted @SqlEvenQuotes String sql, int[] columnIndexes) throws SQLException;

    @Positive
    default long executeLargeUpdate(@Untainted @SqlEvenQuotes String sql, String[] columnNames) throws SQLException;

    @Positive
    default String enquoteLiteral(String val) throws SQLException;

    @Positive
    default String enquoteIdentifier(String identifier, boolean alwaysQuote) throws SQLException;

    @Positive
    default boolean isSimpleIdentifier(String identifier) throws SQLException;

    @Positive
    default String enquoteNCharLiteral(String val) throws SQLException;
    @Positive
}
