
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package polyglot.pth;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMMA = 11;
  public static final int BUILD = 13;
  public static final int LPAREN = 4;
  public static final int RPAREN = 5;
  public static final int error = 1;
  public static final int RBRACK = 7;
  public static final int IDENT = 2;
  public static final int RBRACE = 9;
  public static final int LBRACK = 6;
  public static final int SEMICOLON = 10;
  public static final int STRING_LITERAL = 3;
  public static final int EOF = 0;
  public static final int LBRACE = 8;
  public static final int PLUS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "STRING_LITERAL",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "COMMA",
  "PLUS",
  "BUILD"
  };
}

