
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package java_cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WITH = 11;
  public static final int CODE_STRING = 36;
  public static final int PARSER = 6;
  public static final int SEMI = 13;
  public static final int INIT = 9;
  public static final int STAR = 15;
  public static final int SCAN = 10;
  public static final int BAR = 19;
  public static final int LT = 29;
  public static final int COMMA = 14;
  public static final int NON = 8;
  public static final int CLASS = 34;
  public static final int CODE = 4;
  public static final int ID = 35;
  public static final int DOT = 16;
  public static final int LEFT = 21;
  public static final int EOF = 0;
  public static final int SUPER = 31;
  public static final int error = 1;
  public static final int START = 12;
  public static final int NONTERMINAL = 27;
  public static final int ACTION = 5;
  public static final int LBRACK = 25;
  public static final int IMPORT = 3;
  public static final int COLON = 17;
  public static final int RBRACK = 26;
  public static final int PACKAGE = 2;
  public static final int NONASSOC = 23;
  public static final int EXTENDS = 32;
  public static final int PRECEDENCE = 20;
  public static final int QUESTION = 30;
  public static final int PERCENT_PREC = 24;
  public static final int TERMINAL = 7;
  public static final int RIGHT = 22;
  public static final int IMPLEMENTS = 33;
  public static final int GT = 28;
  public static final int COLON_COLON_EQUALS = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PACKAGE",
  "IMPORT",
  "CODE",
  "ACTION",
  "PARSER",
  "TERMINAL",
  "NON",
  "INIT",
  "SCAN",
  "WITH",
  "START",
  "SEMI",
  "COMMA",
  "STAR",
  "DOT",
  "COLON",
  "COLON_COLON_EQUALS",
  "BAR",
  "PRECEDENCE",
  "LEFT",
  "RIGHT",
  "NONASSOC",
  "PERCENT_PREC",
  "LBRACK",
  "RBRACK",
  "NONTERMINAL",
  "GT",
  "LT",
  "QUESTION",
  "SUPER",
  "EXTENDS",
  "IMPLEMENTS",
  "CLASS",
  "ID",
  "CODE_STRING"
  };
}

