
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package ppg.parse;

/** CUP generated class containing symbol constants. */
public class Constant {
  /* terminals */
  public static final int TERMINAL = 14;
  public static final int EXTENDS = 24;
  public static final int STRING_CONST = 41;
  public static final int CODE_STR = 43;
  public static final int NONTERMINAL = 15;
  public static final int SEMI = 10;
  public static final int LT = 20;
  public static final int COLON_COLON_EQUALS = 12;
  public static final int CLASS = 25;
  public static final int error = 1;
  public static final int QUESTION = 22;
  public static final int DROP = 4;
  public static final int IMPORT = 27;
  public static final int NONASSOC = 40;
  public static final int TRANSFER = 5;
  public static final int PACKAGE = 26;
  public static final int RIGHT = 39;
  public static final int SCAN = 33;
  public static final int ID = 42;
  public static final int INCLUDE = 2;
  public static final int EOF = 0;
  public static final int PERCENT_PREC = 16;
  public static final int COMMA = 9;
  public static final int PARSER = 30;
  public static final int SUPER = 23;
  public static final int PRECEDENCE = 37;
  public static final int LEFT = 38;
  public static final int EXTEND = 44;
  public static final int DOT = 17;
  public static final int IMPLEMENTS = 8;
  public static final int COLON = 11;
  public static final int NON = 31;
  public static final int GT = 21;
  public static final int WITH = 34;
  public static final int OVERRIDE = 45;
  public static final int RBRACK = 19;
  public static final int CODE = 28;
  public static final int INIT = 32;
  public static final int BAR = 13;
  public static final int RBRACE = 7;
  public static final int ACTION = 29;
  public static final int STAR = 36;
  public static final int LBRACK = 18;
  public static final int START = 35;
  public static final int TO = 3;
  public static final int LBRACE = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INCLUDE",
  "TO",
  "DROP",
  "TRANSFER",
  "LBRACE",
  "RBRACE",
  "IMPLEMENTS",
  "COMMA",
  "SEMI",
  "COLON",
  "COLON_COLON_EQUALS",
  "BAR",
  "TERMINAL",
  "NONTERMINAL",
  "PERCENT_PREC",
  "DOT",
  "LBRACK",
  "RBRACK",
  "LT",
  "GT",
  "QUESTION",
  "SUPER",
  "EXTENDS",
  "CLASS",
  "PACKAGE",
  "IMPORT",
  "CODE",
  "ACTION",
  "PARSER",
  "NON",
  "INIT",
  "SCAN",
  "WITH",
  "START",
  "STAR",
  "PRECEDENCE",
  "LEFT",
  "RIGHT",
  "NONASSOC",
  "STRING_CONST",
  "ID",
  "CODE_STR",
  "EXTEND",
  "OVERRIDE"
  };
}

