/*
    @Positive
 * Copyright (c) 1996, 2020, Oracle and/or its affiliates. All rights reserved.
    @Positive
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
    @Positive
 *
    @Positive
 * This code is free software; you can redistribute it and/or modify it
    @Positive
 * under the terms of the GNU General Public License version 2 only, as
    @Positive
 * published by the Free Software Foundation.  Oracle designates this
    @Positive
 * particular file as subject to the "Classpath" exception as provided
    @Positive
 * by Oracle in the LICENSE file that accompanied this code.
    @Positive
 *
    @Positive
 * This code is distributed in the hope that it will be useful, but WITHOUT
    @Positive
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    @Positive
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    @Positive
 * version 2 for more details (a copy is included in the LICENSE file that
    @Positive
 * accompanied this code).
    @Positive
 *
    @Positive
 * You should have received a copy of the GNU General Public License version
    @Positive
 * 2 along with this work; if not, write to the Free Software Foundation,
    @Positive
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
    @Positive
 *
    @Positive
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
    @Positive
 * or visit www.oracle.com if you need additional information or have any
    @Positive
 * questions.
    @Positive
 */
    @Positive
package java.sql;

    @Positive
import org.checkerframework.checker.sqlquotes.qual.SqlEvenQuotes;
    @Positive
import org.checkerframework.checker.tainting.qual.Untainted;
    @Positive
import java.util.regex.Pattern;
    @Positive
import static java.util.stream.Collectors.joining;

    @Positive
public interface Statement extends Wrapper, AutoCloseable {

    @Positive
    ResultSet executeQuery(@Untainted @SqlEvenQuotes String sql) throws SQLException;

    @Positive
    int executeUpdate(@Untainted @SqlEvenQuotes String sql) throws SQLException;

    @Positive
    void close() throws SQLException;

    @Positive
    int getMaxFieldSize() throws SQLException;

    @Positive
    void setMaxFieldSize(int max) throws SQLException;

    @Positive
    int getMaxRows() throws SQLException;

    @Positive
    void setMaxRows(int max) throws SQLException;

    @Positive
    void setEscapeProcessing(boolean enable) throws SQLException;

    @Positive
    int getQueryTimeout() throws SQLException;

    @Positive
    void setQueryTimeout(int seconds) throws SQLException;

    @Positive
    void cancel() throws SQLException;

    @Positive
    SQLWarning getWarnings() throws SQLException;

    @Positive
    void clearWarnings() throws SQLException;

    @Positive
    void setCursorName(String name) throws SQLException;

    @Positive
    boolean execute(@Untainted @SqlEvenQuotes String sql) throws SQLException;

    @Positive
    ResultSet getResultSet() throws SQLException;

    @Positive
    int getUpdateCount() throws SQLException;

    @Positive
    boolean getMoreResults() throws SQLException;

    @Positive
    void setFetchDirection(int direction) throws SQLException;

    @Positive
    int getFetchDirection() throws SQLException;

    @Positive
    void setFetchSize(int rows) throws SQLException;

    @Positive
    int getFetchSize() throws SQLException;

    @Positive
    int getResultSetConcurrency() throws SQLException;

    @Positive
    int getResultSetType() throws SQLException;

    @Positive
    void addBatch(@Untainted @SqlEvenQuotes String sql) throws SQLException;

    @Positive
    void clearBatch() throws SQLException;

    @Positive
    int[] executeBatch() throws SQLException;

    @Positive
    Connection getConnection() throws SQLException;

    @Positive
    int CLOSE_CURRENT_RESULT;

    @Positive
    int KEEP_CURRENT_RESULT;

    @Positive
    int CLOSE_ALL_RESULTS;

    @Positive
    int SUCCESS_NO_INFO;

    @Positive
    int EXECUTE_FAILED;

    @Positive
    int RETURN_GENERATED_KEYS;

    @Positive
    int NO_GENERATED_KEYS;

    @Positive
    boolean getMoreResults(int current) throws SQLException;

    @Positive
    ResultSet getGeneratedKeys() throws SQLException;

    @Positive
    int executeUpdate(@Untainted @SqlEvenQuotes String sql, int autoGeneratedKeys) throws SQLException;

    @Positive
    int executeUpdate(@Untainted @SqlEvenQuotes String sql, int[] columnIndexes) throws SQLException;

    @Positive
    int executeUpdate(@Untainted @SqlEvenQuotes String sql, String[] columnNames) throws SQLException;

    @Positive
    boolean execute(@Untainted @SqlEvenQuotes String sql, int autoGeneratedKeys) throws SQLException;

    @Positive
    boolean execute(@Untainted @SqlEvenQuotes String sql, int[] columnIndexes) throws SQLException;

    @Positive
    boolean execute(@Untainted @SqlEvenQuotes String sql, String[] columnNames) throws SQLException;

    @Positive
    int getResultSetHoldability() throws SQLException;

    @Positive
    boolean isClosed() throws SQLException;

    @Positive
    void setPoolable(boolean poolable) throws SQLException;

    @Positive
    boolean isPoolable() throws SQLException;

    @Positive
    public void closeOnCompletion() throws SQLException;

    @Positive
    public boolean isCloseOnCompletion() throws SQLException;

    @Positive
    default long getLargeUpdateCount() throws SQLException;

    @Positive
    default void setLargeMaxRows(long max) throws SQLException;

    @Positive
    default long getLargeMaxRows() throws SQLException;

    @Positive
    default long[] executeLargeBatch() throws SQLException;

    @Positive
    default long executeLargeUpdate(@Untainted @SqlEvenQuotes String sql) throws SQLException;

    @Positive
    default long executeLargeUpdate(@Untainted @SqlEvenQuotes String sql, int autoGeneratedKeys) throws SQLException;

    @Positive
    default long executeLargeUpdate(@Untainted @SqlEvenQuotes String sql, int[] columnIndexes) throws SQLException;

    @Positive
    default long executeLargeUpdate(@Untainted @SqlEvenQuotes String sql, String[] columnNames) throws SQLException;

    @Positive
    default String enquoteLiteral(String val) throws SQLException;

    @Positive
    default String enquoteIdentifier(String identifier, boolean alwaysQuote) throws SQLException;

    @Positive
    default boolean isSimpleIdentifier(String identifier) throws SQLException;

    @Positive
    default String enquoteNCharLiteral(String val) throws SQLException;
    @Positive
}

// CFWR semantic augmentation - variant 0
